baseURL: https://danaes.github.io
languageCode: es-es
defaultContentLanguage: es
title: "Danaes"
theme: "toha"

languages:
  es:
    languageName: Spanish
    weight: 1
  en:
    languageName: English
    weight: 2

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

enableEmoji: true


params:
  background: /images/site/background.jpg

  websiteTitle: "Blog Danaes | Official web page"

  enableBlogPost: false

  enableTOC: true

  newsletter:
    enable: false

  lazyload:
    enable: true

  seo:
    enable: true

  features:
    analytics:
      enabled: true
      google:
        id: G-QH6WVZ6EG6


privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: false
    disable: false
    respectDoNotTrack: false
    useSessionStorage: false
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true