baseURL: https://danaes.github.io
languageCode: es-es
defaultContentLanguage: es
title: "Danaes"
theme: "toha"

languages:
  es:
    languageName: Spanish
    weight: 1
  en:
    languageName: English
    weight: 2

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

enableEmoji: true


params:
  background: /images/site/background.jpg

  websiteTitle: "Blog Danaes | Official web page"

  enableBlogPost: false

  enableTOC: true

  newsletter:
    enable: false

  lazyload:
    enable: trues

  seo:
    enable: true


disableKinds: ["taxonomy", "taxonomyTerm"]