baseURL: https://danaes.github.io

languageCode: es-es
title: "Blog_dag"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

outputs:
  home:
  - HTML
  - RSS
  - JSON

enableEmoji: true

params:
  enableBlogPost: true

  enableTOC: true

  newsletter:
    enable: false
